/**
 * SEED ARTWORKS — PRD §37.1, §11.
 *
 * 65 pieces across 10 artists (5–8 each, §37.1). Every §11.2 tag-coverage floor
 * is asserted by `scripts/validate-seed.ts`, which runs in CI:
 *
 *   every style  on >= 3 works   every colour on >= 4 works
 *   every mood   on >= 5 works   every room   on >= 8 works
 *   >= 4 works in each boldness band 1-3 / 4-7 / 8-10
 *   >= 8 works in each size bucket   >= 6 works in each budget band
 *
 * "Without these floors, plausible survey answers produce an empty or
 *  repetitive feed, and the demo dies on stage." (§11.2)
 *
 * `size_category` and all four rental rungs are DERIVED at build time (§9.5,
 * §7.2) — they are never authored here, so they cannot disagree.
 *
 * Two rows are load-bearing fixtures for §12.7 and must not be edited without
 * updating `score.test.ts`:
 *   "Blue Horizon" — 48x36, $1,200 -> Alex scores it 100
 *   "Ferry Light"  — 24x18, $600   -> Alex scores it 49
 */

export interface SeedArtwork {
  artist: string
  title: string
  year: number
  medium: string
  materials: string
  w: number
  h: number
  /** Dollars. Drives the whole ladder (§7.2). */
  price: number
  boldness: number
  styles: string[]
  colors: string[]
  moods: string[]
  rooms: string[]
  description: string
  note: string
  featured?: boolean
  /**
   * Authored composition mode, passed to the generator (`GenContext.mode`).
   *
   * The descriptions above are specific — "a single band across the lower
   * third", "one horizontal rule stopping four inches short of the edge". A
   * generator left to choose its own composition will eventually contradict the
   * caption sitting beside it on the detail page, and a caption that describes a
   * different painting is worse than no caption at all.
   *
   * colorField 0 registers · 1 one mass · 2 diagonal split · 3 veils
   * minimal    0 rule+disc · 1 disc+rule · 2 bars · 3 fields · 4 arc · 5 stroke · 6 gestural
   * stencil    0 burst · 1 bars · 2 squares · 3 chevrons
   * lightStudy 0 radial · 1 parallel · 2 sweeping arc
   * halftone   0 disc · 1 rings · 2 squares
   * dreamscape 1 forces the freestanding doorway
   */
  mode?: number
}

export const ARTWORKS: SeedArtwork[] = [
  // ------------------------------------------------------------------ Maya Chen (8)
  {
    artist: 'maya-puterman', title: 'Blue Horizon', year: 2025,
    medium: 'Acrylic on canvas', materials: 'Acrylic, gesso, linen',
    w: 48, h: 36, price: 1200, boldness: 4, featured: true,
    styles: ['abstract', 'contemporary'], colors: ['blue', 'neutral'], moods: ['calm'],
    rooms: ['living-room', 'bedroom', 'office'],
    mode: 0,
    description: 'A single band of deep blue settles across the lower third, carried on thirty-one washes of thinned acrylic. Up close the surface is almost entirely edge; from across a room it reads as one uninterrupted breath of colour.',
    note: 'I painted this the week my father came out of hospital. I wanted something that lowered the room instead of asking anything of it.',
  },
  {
    artist: 'maya-puterman', title: 'Tidal Register', year: 2025,
    medium: 'Acrylic on canvas', materials: 'Acrylic, marble dust, canvas',
    w: 40, h: 30, price: 1400, boldness: 5,
    styles: ['abstract'], colors: ['blue', 'green', 'neutral'], moods: ['calm', 'sophisticated'],
    rooms: ['living-room', 'office'],
    mode: 0,
    description: 'Blue-green washes stack in uneven horizontal registers, each one recording where the previous layer had already dried. Marble dust gives the upper field a chalky tooth that catches side light.',
    note: 'The bands are not planned. They are the tide line of whatever I did the day before.',
  },
  {
    artist: 'maya-puterman', title: 'Slow Water', year: 2024,
    medium: 'Acrylic on panel', materials: 'Acrylic on birch panel',
    w: 18, h: 18, price: 420, boldness: 3,
    styles: ['abstract', 'contemporary'], colors: ['blue', 'neutral', 'monochrome'], moods: ['calm'],
    rooms: ['bedroom', 'hallway'],
    mode: 1,
    description: 'A square of pale blue that darkens almost imperceptibly toward one corner. The only incident is a soft-edged form near the centre, more suggestion than shape.',
    note: 'Made to be looked at for a long time, or not at all. Both are fine.',
  },
  {
    artist: 'maya-puterman', title: 'Ninety Layers', year: 2025,
    medium: 'Acrylic on canvas', materials: 'Acrylic, pigment, cotton canvas',
    w: 60, h: 44, price: 2600, boldness: 6, featured: true,
    styles: ['abstract'], colors: ['earth', 'neutral', 'orange'], moods: ['sophisticated', 'calm'],
    rooms: ['living-room', 'dining-room'],
    mode: 3,
    description: 'Ochre and raw umber built up over four months until the surface stopped being paint and started being ground. A single dark gesture crosses the field just below centre.',
    note: 'I counted for a while and then stopped. Ninety is a guess.',
  },
  {
    artist: 'maya-puterman', title: 'Field Notes, Morning', year: 2024,
    medium: 'Acrylic on paper', materials: 'Acrylic on cotton rag',
    w: 18, h: 14, price: 340, boldness: 3,
    styles: ['abstract'], colors: ['neutral', 'green', 'earth'], moods: ['calm', 'cozy'],
    rooms: ['bedroom', 'office', 'hallway'],
    mode: 1,
    description: 'A small study in warm grey and pale sage, made in a single sitting before the light changed. The paper edge is left visible.',
    note: 'One of about forty of these. They are how I decide what the big ones are going to be.',
  },
  {
    artist: 'maya-puterman', title: 'Terracotta Interval', year: 2025,
    medium: 'Oil on canvas', materials: 'Oil, cold wax, linen',
    w: 36, h: 36, price: 1500, boldness: 6,
    styles: ['abstract', 'contemporary'], colors: ['earth', 'orange', 'red'], moods: ['cozy', 'sophisticated'],
    rooms: ['living-room', 'dining-room'],
    mode: 0,
    description: 'Burnt orange and clay, held apart by a band of near-white that does not quite reach either edge. Cold wax gives the whole surface a matte, plastered quality.',
    note: 'The gap in the middle is the piece. Everything else is there to make the gap possible.',
  },
  {
    artist: 'maya-puterman', title: 'The Long Wash', year: 2026,
    medium: 'Acrylic on canvas', materials: 'Acrylic on stretched linen',
    w: 72, h: 48, price: 4200, boldness: 5,
    styles: ['abstract'], colors: ['blue', 'neutral', 'monochrome'], moods: ['calm', 'sophisticated'],
    rooms: ['living-room'],
    mode: 2,
    description: 'Six feet of graduated blue, poured in one continuous pass on a levelled floor and left to find its own edges over nine days. The largest single-pour work in the series.',
    note: 'You get one attempt. I ruined four canvases before this one behaved.',
  },
  {
    artist: 'maya-puterman', title: 'Verdigris', year: 2024,
    medium: 'Acrylic on panel', materials: 'Acrylic, copper pigment, panel',
    w: 30, h: 22, price: 820, boldness: 4,
    styles: ['abstract', 'contemporary'], colors: ['green', 'neutral', 'earth'], moods: ['calm', 'inspiring'],
    rooms: ['office', 'hallway'],
    mode: 0,
    description: 'Oxidised greens over a warm grey ground, with copper pigment worked into the upper edge so the colour shifts as you walk past it.',
    note: 'Named for the roof of the building where I had my first studio.',
  },

  // ------------------------------------------------------- Jordan Williams (7)
  {
    artist: 'tobias-williams', title: '3:14 AM, Wabash', year: 2025,
    medium: 'Archival pigment print', materials: 'Archival pigment on cotton rag',
    w: 36, h: 24, price: 1100, boldness: 7, featured: true,
    styles: ['photography'], colors: ['monochrome', 'yellow', 'orange'], moods: ['dramatic', 'energetic'],
    rooms: ['living-room', 'office'],
    mode: 1,
    description: 'Ninety seconds under the elevated tracks. Sodium light drags into long amber ribbons across an otherwise black frame; the girders stay perfectly still.',
    note: 'No correction, no stacking. What the sensor collected in ninety seconds is what you are looking at.',
  },
  {
    artist: 'tobias-williams', title: 'Nightwork', year: 2024,
    medium: 'Archival pigment print', materials: 'Archival pigment on baryta',
    w: 24, h: 18, price: 620, boldness: 6,
    styles: ['photography'], colors: ['monochrome', 'blue', 'neutral'], moods: ['dramatic', 'sophisticated'],
    rooms: ['office', 'hallway'],
    mode: 1,
    description: 'A cold blue cast over near-total darkness, broken by three vertical filaments of light where a service crew worked through the night.',
    note: 'They let me stand there for two hours. Nobody asked what I was doing.',
  },
  {
    artist: 'tobias-williams', title: 'Ninety Seconds', year: 2025,
    medium: 'Archival pigment print', materials: 'Archival pigment on cotton rag',
    w: 48, h: 32, price: 1350, boldness: 8,
    styles: ['photography'], colors: ['monochrome', 'orange', 'yellow'], moods: ['dramatic', 'energetic'],
    rooms: ['living-room'],
    mode: 2,
    description: 'The exposure that gave the series its name. Headlights on a wet road resolve into a single sweeping arc, bright enough to read as a physical object.',
    note: 'I timed it on a kitchen stopwatch. Still do.',
  },
  {
    artist: 'tobias-williams', title: 'Cut Piece No. 4', year: 2025,
    medium: 'Spray paint and stencil on panel', materials: 'Aerosol, hand-cut stencil, plywood',
    w: 30, h: 30, price: 760, boldness: 9,
    styles: ['street', 'contemporary'], colors: ['red', 'monochrome', 'neutral'], moods: ['energetic', 'playful'],
    rooms: ['office', 'living-room'],
    mode: 0,
    description: 'A hand-cut radial stencil laid over two passes of red, with the overspray left in. The plywood grain shows through where the paint went thin.',
    note: 'Cut the stencil with a scalpel over three evenings. Used it once, then it fell apart.',
  },
  {
    artist: 'tobias-williams', title: 'Overspray', year: 2026,
    medium: 'Aerosol on canvas', materials: 'Aerosol, stencil, canvas',
    w: 40, h: 30, price: 1250, boldness: 9,
    styles: ['street'], colors: ['vibrant', 'red', 'orange'], moods: ['energetic', 'dramatic'],
    rooms: ['living-room', 'office'],
    mode: 3,
    description: 'Four stencil layers in fluorescent red and orange, deliberately misregistered. Drips are left where they fell.',
    note: 'The misregistration is the whole point. A clean print of this would be worthless.',
  },
  {
    artist: 'tobias-williams', title: 'Stencil Study (Red)', year: 2024,
    medium: 'Aerosol on paper', materials: 'Aerosol on heavy stock',
    w: 16, h: 16, price: 290, boldness: 8,
    styles: ['street'], colors: ['red', 'monochrome', 'neutral'], moods: ['energetic', 'playful'],
    rooms: ['office', 'hallway', 'bedroom'],
    mode: 2,
    description: 'A small, fast study — one stencil, one colour, three minutes. The speckle at the edges is where the can was held too close.',
    note: 'These are warm-ups. I have hundreds. This one I liked.',
  },
  {
    artist: 'tobias-williams', title: 'Lake Shore, Long', year: 2026,
    medium: 'Archival pigment print', materials: 'Archival pigment on cotton rag',
    w: 60, h: 40, price: 2900, boldness: 7, featured: true,
    styles: ['photography'], colors: ['monochrome', 'blue', 'neutral'], moods: ['dramatic', 'calm'],
    rooms: ['living-room', 'dining-room'],
    mode: 1,
    description: 'A four-minute exposure of Lake Michigan in February. The water has gone completely smooth; only the horizon and a single distant light survive the length of the frame.',
    note: 'It was eleven degrees. The battery died right after this one.',
  },

  // --------------------------------------------------------- Sofia Martinez (7)
  {
    artist: 'ella-lodewyk', title: 'Mesa, Six O’Clock', year: 2025,
    medium: 'Oil on linen', materials: 'Oil on stretched linen',
    w: 36, h: 24, price: 1300, boldness: 5, featured: true,
    styles: ['impressionist', 'landscape'], colors: ['orange', 'purple', 'earth'], moods: ['calm', 'inspiring'],
    rooms: ['living-room', 'dining-room'],
    description: 'The west mesa at the exact moment the rock turns from orange to violet, built from several thousand short unblended strokes. The colour mixes in your eye, not on the palette.',
    note: 'Ninety minutes a day, eleven days. On the twelfth it rained and I stopped.',
  },
  {
    artist: 'ella-lodewyk', title: 'Chamisa in Flower', year: 2024,
    medium: 'Oil on panel', materials: 'Oil on gessoed panel',
    w: 24, h: 20, price: 680, boldness: 6,
    styles: ['impressionist'], colors: ['yellow', 'green', 'earth'], moods: ['playful', 'cozy'],
    rooms: ['dining-room', 'bedroom'],
    description: 'A field of yellow chamisa in late September, painted so densely that the ground barely shows. Small strokes of sage and dusty green hold the yellow from going flat.',
    note: 'It smells appalling in bloom. The colour makes up for it.',
  },
  {
    artist: 'ella-lodewyk', title: 'Arroyo, After Rain', year: 2024,
    medium: 'Oil on linen', materials: 'Oil on linen',
    w: 30, h: 22, price: 780, boldness: 4,
    styles: ['impressionist', 'landscape'], colors: ['green', 'earth', 'neutral'], moods: ['calm', 'cozy'],
    rooms: ['bedroom', 'hallway'],
    description: 'The dry wash behind the studio, briefly running. Wet sand takes on a green cast that lasts about two hours a year.',
    note: 'I have waited for this four times and got it twice.',
  },
  {
    artist: 'ella-lodewyk', title: 'The Same Three Mesas', year: 2026,
    medium: 'Oil on linen', materials: 'Oil on stretched linen',
    w: 72, h: 40, price: 3900, boldness: 6,
    styles: ['landscape', 'impressionist'], colors: ['orange', 'purple', 'red'], moods: ['inspiring', 'sophisticated'],
    rooms: ['living-room'],
    description: 'Six feet of high desert at the end of the day, the culmination of eleven years spent on one view. Three ridgelines recede into violet; the foreground stays hot.',
    note: 'People ask when I will paint something else. I do not have an answer they like.',
  },
  {
    artist: 'ella-lodewyk', title: 'Piñon Shadow', year: 2023,
    medium: 'Gouache on paper', materials: 'Gouache on cotton rag',
    w: 18, h: 14, price: 330, boldness: 3,
    styles: ['impressionist'], colors: ['green', 'earth', 'neutral'], moods: ['calm', 'cozy'],
    rooms: ['bedroom', 'office', 'hallway'],
    description: 'A quiet study of shadow under a piñon at midday, where the ground goes blue-green in the shade and bone-pale two inches away.',
    note: 'Painted sitting on a rock. There is a bit of the rock in the paint.',
  },
  {
    artist: 'ella-lodewyk', title: 'Last Light, Tesuque', year: 2025,
    medium: 'Oil on linen', materials: 'Oil on linen',
    w: 44, h: 32, price: 1650, boldness: 7,
    styles: ['landscape', 'impressionist'], colors: ['orange', 'yellow', 'red'], moods: ['inspiring', 'energetic'],
    rooms: ['living-room', 'dining-room'],
    description: 'The hottest painting in the series — cadmium orange and lemon laid side by side with almost no mixing, so the whole canvas vibrates at the edges.',
    note: 'The last four minutes before the sun goes behind the ridge. You do not get to plan.',
  },
  {
    artist: 'ella-lodewyk', title: 'Snow on Sangre de Cristo', year: 2024,
    medium: 'Oil on panel', materials: 'Oil on gessoed panel',
    w: 20, h: 16, price: 520, boldness: 4,
    styles: ['landscape'], colors: ['neutral', 'purple', 'blue'], moods: ['calm', 'sophisticated'],
    rooms: ['bedroom', 'hallway', 'office'],
    description: 'First snow on the range, painted from a parking lot. Warm greys in the foreground give way to a cold violet at the peaks.',
    note: 'Small, because it was too cold to stand there for long.',
  },

  // ----------------------------------------------------------- Ethan Brooks (6)
  {
    artist: 'finn-kelly', title: 'Rule, Interrupted', year: 2025,
    medium: 'Ink on cotton rag', materials: 'Sumi ink on hand-torn cotton rag',
    w: 30, h: 40, price: 980, boldness: 2, featured: true,
    styles: ['minimalist'], colors: ['neutral', 'monochrome', 'earth'], moods: ['calm', 'sophisticated'],
    rooms: ['office', 'bedroom', 'living-room'],
    mode: 0,
    description: 'One horizontal rule, drawn in a single pass, stopping four inches short of the right edge. Nothing else is on the sheet.',
    note: 'The version where the line reaches the edge took two seconds longer and was much worse.',
  },
  {
    artist: 'finn-kelly', title: 'Two Decisions', year: 2024,
    medium: 'Ink on cotton rag', materials: 'Sumi ink, cotton rag, deckle edge',
    w: 15, h: 18, price: 380, boldness: 2,
    styles: ['minimalist'], colors: ['monochrome', 'neutral', 'earth'], moods: ['calm', 'sophisticated'],
    rooms: ['office', 'hallway', 'bedroom'],
    mode: 0,
    description: 'A short rule and a single dot, placed off-centre in both directions. The deckle edge is left raw on all four sides.',
    note: 'Two marks. It took most of a week to decide where the second one went.',
  },
  {
    artist: 'finn-kelly', title: 'Deckle No. 9', year: 2025,
    medium: 'Collage on rag', materials: 'Torn rag, wheat paste, graphite',
    w: 22, h: 30, price: 640, boldness: 3,
    styles: ['mixed-media', 'minimalist'], colors: ['earth', 'neutral', 'monochrome'], moods: ['calm', 'cozy'],
    rooms: ['bedroom', 'hallway'],
    description: 'Three torn rectangles of undyed rag, overlapped and pasted, with a faint graphite line running underneath all three.',
    note: 'The tear is the drawing. I stopped pretending otherwise around 2022.',
  },
  {
    artist: 'finn-kelly', title: 'Everything Removed', year: 2026,
    medium: 'Acrylic on canvas', materials: 'Acrylic on cotton canvas',
    w: 52, h: 40, price: 2200, boldness: 1,
    styles: ['minimalist'], colors: ['neutral', 'monochrome', 'earth'], moods: ['calm', 'sophisticated'],
    rooms: ['living-room', 'office'],
    mode: 0,
    description: 'A four-foot field of warm off-white with a single hairline division low on the left. The quietest work in the practice, and the largest.',
    note: 'There were nine other elements. I took them all out over about five months.',
  },
  {
    artist: 'finn-kelly', title: 'Fold, Twice', year: 2023,
    medium: 'Ink on paper', materials: 'Sumi ink on folded rag',
    w: 14, h: 18, price: 260, boldness: 2,
    styles: ['minimalist', 'mixed-media'], colors: ['monochrome'], moods: ['sophisticated', 'calm'],
    rooms: ['office', 'hallway'],
    mode: 2,
    description: 'The sheet was folded twice before it was drawn on, and the ink stopped where the creases were. The folds are the composition.',
    note: 'Bookbinding does this to you. You start seeing the paper as the work.',
  },
  {
    artist: 'finn-kelly', title: 'Margin', year: 2025,
    medium: 'Acrylic on panel', materials: 'Acrylic on birch panel',
    w: 36, h: 24, price: 1150, boldness: 3,
    styles: ['minimalist'], colors: ['neutral', 'blue', 'monochrome'], moods: ['calm', 'sophisticated'],
    rooms: ['living-room', 'bedroom', 'office'],
    mode: 3,
    description: 'A pale field with a narrow band of cold blue holding the left quarter. Nothing is centred, and nothing is quite where you expect it.',
    note: 'Named after the part of a page nobody looks at, which is where I put everything.',
  },

  // -------------------------------------------------------------- Ava Patel (7)
  {
    artist: 'grace-minakowski', title: 'Neighbour, Remembered', year: 2025,
    medium: 'Acrylic on panel', materials: 'Acrylic and oil stick on birch',
    w: 30, h: 24, price: 890, boldness: 6,
    styles: ['portrait', 'contemporary'], colors: ['red', 'earth', 'orange'], moods: ['sophisticated', 'dramatic'],
    rooms: ['living-room', 'hallway'],
    description: 'A head built from six overlapping flat planes in oxide red and umber. The features never resolve, but the posture is unmistakable.',
    note: 'They lived across the hall for four years. I painted them from memory a week after they moved out.',
  },
  {
    artist: 'grace-minakowski', title: 'My Grandmother, Twice', year: 2025,
    medium: 'Oil on panel', materials: 'Oil and oil stick on panel',
    w: 40, h: 30, price: 1450, boldness: 6, featured: true,
    styles: ['portrait'], colors: ['earth', 'purple', 'red'], moods: ['cozy', 'sophisticated'],
    rooms: ['living-room', 'dining-room'],
    description: 'Two overlapping profiles of the same woman, painted a year apart and eventually resolved onto one panel. The violet ground belonged to the second sitting.',
    note: 'The second one is more accurate. The first one is more her.',
  },
  {
    artist: 'grace-minakowski', title: 'Sitter with No Room', year: 2026,
    medium: 'Acrylic on canvas', materials: 'Acrylic on cotton canvas',
    w: 36, h: 28, price: 1300, boldness: 7,
    styles: ['surreal', 'portrait'], colors: ['purple', 'vibrant', 'red'], moods: ['dramatic', 'inspiring'],
    rooms: ['living-room', 'office'],
    mode: 0,
    description: 'A figure seated in a space that does not close — the horizon runs behind them at two different heights, and their shadow falls toward the light.',
    note: 'The backgrounds started misbehaving about a year ago. I decided to let them.',
  },
  {
    artist: 'grace-minakowski', title: 'Plane, Face, Plane', year: 2024,
    medium: 'Acrylic on panel', materials: 'Acrylic on birch panel',
    w: 18, h: 14, price: 360, boldness: 5,
    styles: ['portrait', 'contemporary'], colors: ['red', 'neutral', 'monochrome'], moods: ['sophisticated'],
    rooms: ['office', 'hallway', 'bedroom'],
    description: 'A small study: three planes, one of which happens to be a face. Removing the fourth is what made it work.',
    note: 'These studies are how I find out whether a person is going to hold up at size.',
  },
  {
    artist: 'grace-minakowski', title: 'The Room Behaves', year: 2026,
    medium: 'Acrylic on canvas', materials: 'Acrylic and oil stick on canvas',
    w: 48, h: 36, price: 1900, boldness: 8,
    styles: ['surreal'], colors: ['purple', 'orange', 'red'], moods: ['dramatic', 'playful'],
    rooms: ['living-room', 'dining-room'],
    mode: 1,
    description: 'A domestic interior in violet and burnt orange where a doorway stands unattached in open floor, casting a shadow four times its own length.',
    note: 'Titled optimistically. It does not.',
  },
  {
    artist: 'grace-minakowski', title: 'Anonymous (Blue)', year: 2024,
    medium: 'Acrylic on panel', materials: 'Acrylic on birch panel',
    w: 18, h: 14, price: 390, boldness: 5,
    styles: ['portrait', 'contemporary'], colors: ['blue', 'neutral', 'monochrome'], moods: ['calm', 'sophisticated'],
    rooms: ['bedroom', 'office'],
    description: 'The quietest portrait in the series. Cool blue planes over a grey ground; the sitter is turned almost entirely away.',
    note: 'They asked not to be recognisable. That turned out to improve it.',
  },
  {
    artist: 'grace-minakowski', title: 'Six Faces, One Week', year: 2026,
    medium: 'Acrylic on canvas', materials: 'Acrylic and oil stick on canvas',
    w: 66, h: 44, price: 4500, boldness: 7,
    styles: ['portrait', 'contemporary'], colors: ['red', 'vibrant', 'purple'], moods: ['dramatic', 'inspiring'],
    rooms: ['living-room'],
    description: 'The largest work to date: six sitters from a single week, painted from memory the following Sunday, overlapping across five and a half feet of canvas.',
    note: 'By the end of the week I could not tell you which features belonged to whom. That is in the painting.',
  },

  // -------------------------------------------------------------- Noah Kim (6)
  {
    artist: 'aayush-shivashankar', title: 'Quarter Arc, Cadmium', year: 2025,
    medium: 'Acrylic on birch panel', materials: 'Acrylic on birch, hand-masked',
    w: 30, h: 30, price: 840, boldness: 7,
    styles: ['contemporary'], colors: ['red', 'yellow', 'monochrome'], moods: ['energetic', 'playful'],
    rooms: ['living-room', 'dining-room', 'office'],
    description: 'A cadmium quarter-arc springing from the lower-left corner into a lemon field, with one thin rule dividing the upper third.',
    note: 'Graph paper first, always. If the drawing is wrong the painting cannot save it.',
  },
  {
    artist: 'aayush-shivashankar', title: 'Graph Paper No. 22', year: 2024,
    medium: 'Acrylic on birch panel', materials: 'Acrylic on birch panel',
    w: 16, h: 16, price: 400, boldness: 5,
    styles: ['contemporary', 'abstract'], colors: ['blue', 'monochrome', 'neutral'], moods: ['sophisticated', 'calm'],
    rooms: ['office', 'hallway'],
    description: 'Four rectangles and one circle on a five-by-five grid, in slate blue and near-black. The grid is never drawn, only obeyed.',
    note: 'Number 22 of an ongoing set. Most of them do not get painted.',
  },
  {
    artist: 'aayush-shivashankar', title: 'Two Circles, One Rule', year: 2025,
    medium: 'Acrylic on birch panel', materials: 'Acrylic on birch panel',
    w: 44, h: 34, price: 1600, boldness: 6, featured: true,
    styles: ['contemporary'], colors: ['blue', 'yellow', 'neutral'], moods: ['sophisticated', 'energetic'],
    rooms: ['living-room', 'office'],
    description: 'Two discs of unequal size, one cropped by the frame, separated by a single vertical rule that is not quite at the golden section.',
    note: 'It is off by about an inch on purpose. On the section it looked smug.',
  },
  {
    artist: 'aayush-shivashankar', title: 'Masked by Hand', year: 2024,
    medium: 'Acrylic on panel', materials: 'Acrylic on birch panel',
    w: 18, h: 18, price: 400, boldness: 6,
    styles: ['contemporary', 'abstract'], colors: ['yellow', 'monochrome', 'neutral'], moods: ['playful', 'energetic'],
    rooms: ['office', 'hallway', 'bedroom'],
    description: 'A small yellow field cut by three black bars at unequal spacing. Every edge is masked by hand, and the slight thickness variation is visible up close.',
    note: 'Tape leaves a better line than a steady wrist. I have tested this extensively.',
  },
  {
    artist: 'aayush-shivashankar', title: 'Division', year: 2026,
    medium: 'Acrylic on canvas', materials: 'Acrylic on cotton canvas',
    w: 60, h: 48, price: 4000, boldness: 8,
    styles: ['contemporary'], colors: ['monochrome', 'red', 'neutral'], moods: ['dramatic', 'sophisticated'],
    rooms: ['living-room', 'dining-room'],
    description: 'Five feet of black and off-white split by one hard vertical, with a single cadmium arc breaking the seam near the base. The largest and most severe work in the series.',
    note: 'The arc is the only thing I changed after the drawing. It needed one mistake.',
  },
  {
    artist: 'aayush-shivashankar', title: 'Blue Field, Two Arcs', year: 2025,
    medium: 'Acrylic on birch panel', materials: 'Acrylic on birch panel',
    w: 36, h: 24, price: 1250, boldness: 4,
    styles: ['contemporary', 'abstract'], colors: ['blue', 'neutral', 'monochrome'], moods: ['calm', 'sophisticated'],
    rooms: ['bedroom', 'living-room', 'office'],
    description: 'A soft slate-blue ground with two pale quarter-arcs at opposite corners. The gentlest painting in the series, and the only one without a rule.',
    note: 'Someone asked for a quiet one. This is what that looks like from me.',
  },

  // -------------------------------------------------------- Layla Thompson (6)
  {
    artist: 'reilly-snyder', title: 'Ferry Light', year: 2024,
    medium: 'Archival pigment print', materials: 'Archival pigment on matte cotton',
    w: 24, h: 18, price: 600, boldness: 3,
    styles: ['photography', 'landscape'], colors: ['blue', 'monochrome'], moods: ['calm'],
    rooms: ['bedroom', 'hallway'],
    description: 'A single navigation light on flat water at first light, printed on matte cotton so the blacks stay open and soft.',
    note: 'Taken from a dock at 5:20. The light went out about a minute later.',
  },
  {
    artist: 'reilly-snyder', title: 'Ridge, 5:40', year: 2025,
    medium: 'Archival pigment print', materials: 'Archival pigment on matte cotton',
    w: 40, h: 26, price: 1200, boldness: 3, featured: true,
    styles: ['photography', 'landscape'], colors: ['neutral', 'blue', 'monochrome'], moods: ['calm', 'sophisticated'],
    rooms: ['bedroom', 'living-room', 'office'],
    description: 'Four ridgelines fading into morning fog, each one a shade paler than the last. There is no black anywhere in the frame.',
    note: 'The mountains are never as contrasty as a screen makes them look. I print for the mountains.',
  },
  {
    artist: 'reilly-snyder', title: 'Fog Bank', year: 2024,
    medium: 'Archival pigment print', materials: 'Archival pigment on matte cotton',
    w: 30, h: 20, price: 760, boldness: 2,
    styles: ['photography'], colors: ['monochrome', 'neutral', 'blue'], moods: ['calm'],
    rooms: ['bedroom', 'hallway', 'office'],
    description: 'Almost nothing: a horizontal band of grey where a valley should be, and one darker mark near the lower edge that turns out to be a tree.',
    note: 'I stood there for forty minutes waiting for it to clear. It did not, which was better.',
  },
  {
    artist: 'reilly-snyder', title: 'Twenty Minutes', year: 2025,
    medium: 'Archival pigment print', materials: 'Archival pigment on matte cotton',
    w: 56, h: 36, price: 2400, boldness: 4,
    styles: ['landscape', 'photography'], colors: ['green', 'neutral', 'blue'], moods: ['calm', 'inspiring'],
    rooms: ['living-room', 'dining-room'],
    description: 'The twenty minutes when fog and ridgeline overlap and neither one wins. Printed large enough that the grain in the fog becomes part of the surface.',
    note: 'The whole series is about this window. It happens maybe nine mornings a year.',
  },
  {
    artist: 'reilly-snyder', title: 'Cove, No Wind', year: 2023,
    medium: 'Archival pigment print', materials: 'Archival pigment on matte cotton',
    w: 16, h: 12, price: 240, boldness: 2,
    styles: ['photography', 'landscape'], colors: ['blue', 'green', 'neutral'], moods: ['calm', 'cozy'],
    rooms: ['bedroom', 'hallway', 'office'],
    description: 'Still water in a small cove, with the far bank reflected so exactly that the horizon has to be inferred.',
    note: 'Small on purpose. It does not need to be big to do what it does.',
  },
  {
    artist: 'reilly-snyder', title: 'Blue Ridge, Matte', year: 2026,
    medium: 'Archival pigment print', materials: 'Archival pigment on matte cotton rag',
    w: 72, h: 44, price: 4800, boldness: 5,
    styles: ['landscape', 'photography'], colors: ['blue', 'green', 'neutral'], moods: ['calm', 'sophisticated'],
    rooms: ['living-room'],
    description: 'Six feet of the Blue Ridge at the moment the blue is literal. Seven receding ranges, printed at a size where each one holds its own detail.',
    note: 'Eleven trips before I got a morning clear enough to justify printing it this large.',
  },

  // ---------------------------------------------------------- Daniel Rivera (6)
  {
    artist: 'dev-dwivedy', title: 'Loud On Purpose', year: 2025,
    medium: 'Four-colour screenprint', materials: 'Screenprint on heavy stock',
    w: 30, h: 30, price: 820, boldness: 10, featured: true,
    styles: ['pop'], colors: ['vibrant', 'red', 'yellow'], moods: ['playful', 'energetic'],
    rooms: ['living-room', 'office', 'dining-room'],
    mode: 0,
    description: 'Four flat colours, no gradients, one hand-cut halftone screen. A red disc sits dead centre and refuses to apologise for it.',
    note: 'I cut that halftone screen in 2016 and I will not be replacing it.',
  },
  {
    artist: 'dev-dwivedy', title: 'Four Flats', year: 2024,
    medium: 'Four-colour screenprint', materials: 'Screenprint on heavy stock',
    w: 24, h: 18, price: 580, boldness: 8,
    styles: ['pop', 'contemporary'], colors: ['yellow', 'blue', 'vibrant'], moods: ['playful', 'energetic'],
    rooms: ['office', 'dining-room', 'hallway'],
    mode: 2,
    description: 'Lemon and cobalt in four flat bands under a rotated dot screen. Legible from thirty feet, which is the entire specification.',
    note: 'If you have to walk up to it, I did it wrong.',
  },
  {
    artist: 'dev-dwivedy', title: 'Halftone Sun', year: 2024,
    medium: 'Three-colour screenprint', materials: 'Screenprint on heavy stock',
    w: 18, h: 18, price: 360, boldness: 9,
    styles: ['pop'], colors: ['orange', 'yellow', 'red'], moods: ['playful', 'energetic'],
    rooms: ['dining-room', 'office', 'hallway'],
    mode: 1,
    description: 'Concentric orange rings under a coarse dot screen, printed slightly out of register so the edges buzz.',
    note: 'The buzz is the register error. I print them one at a time and do not correct it.',
  },
  {
    artist: 'dev-dwivedy', title: 'Gig Poster (Never Printed)', year: 2025,
    medium: 'Acrylic and screenprint on panel', materials: 'Screenprint and acrylic on panel',
    w: 36, h: 24, price: 1150, boldness: 10,
    styles: ['pop', 'street'], colors: ['vibrant', 'purple', 'orange'], moods: ['playful', 'energetic'],
    rooms: ['living-room', 'office'],
    mode: 2,
    description: 'A poster design for a show that was cancelled, enlarged onto panel and finished by hand in fluorescent violet and orange.',
    note: 'The band broke up two days before the run. The artwork was the only thing that survived.',
  },
  {
    artist: 'dev-dwivedy', title: 'The Door Was Not There', year: 2026,
    medium: 'Acrylic on canvas', materials: 'Acrylic and screenprint on canvas',
    w: 48, h: 36, price: 1700, boldness: 9,
    styles: ['surreal', 'pop'], colors: ['orange', 'purple', 'yellow'], moods: ['playful', 'dramatic'],
    rooms: ['living-room', 'dining-room'],
    mode: 1,
    description: 'A flat orange plain under a violet sky, with a freestanding door and two solids hovering just above the horizon. Everything is outlined; nothing casts the right shadow.',
    note: 'Somebody told me pop art cannot be strange. This is my response.',
  },
  {
    artist: 'dev-dwivedy', title: 'Register', year: 2026,
    medium: 'Six-colour screenprint on canvas', materials: 'Screenprint on primed canvas',
    w: 60, h: 40, price: 3900, boldness: 10,
    styles: ['pop', 'contemporary'], colors: ['vibrant', 'red', 'purple'], moods: ['energetic', 'playful'],
    rooms: ['living-room'],
    mode: 2,
    description: 'Five feet of deliberately misregistered colour under two overlapping dot screens. The largest thing ever pulled through this screen, in one edition of one.',
    note: 'Took four people to move the screen. Worth it.',
  },

  // ---------------------------------------------------------- Amara Johnson (6)
  {
    artist: 'angad-miglani', title: 'Ledger, 1961', year: 2025,
    medium: 'Collage and walnut ink', materials: 'Found ledger paper, wheat paste, walnut ink',
    w: 30, h: 24, price: 780, boldness: 5, featured: true,
    styles: ['mixed-media'], colors: ['earth', 'orange', 'neutral'], moods: ['cozy', 'sophisticated'],
    rooms: ['living-room', 'hallway', 'dining-room'],
    description: 'Torn pages from a 1961 hardware-store ledger, layered and wheat-pasted, then drawn over in walnut ink until the columns become architecture.',
    note: 'Bought the whole ledger for four dollars. Someone kept those numbers for a living.',
  },
  {
    artist: 'angad-miglani', title: 'Dress Pattern (Sunday)', year: 2024,
    medium: 'Collage on panel', materials: 'Found tissue pattern, wheat paste, ink, panel',
    w: 24, h: 20, price: 660, boldness: 4,
    styles: ['mixed-media', 'traditional'], colors: ['red', 'earth', 'neutral'], moods: ['cozy', 'inspiring'],
    rooms: ['bedroom', 'dining-room'],
    description: 'Tissue dress-pattern pieces laid over oxide red, with the cutting lines and notches left legible under the ink.',
    note: 'My grandmother made a version of this dress. I found the pattern in an estate sale two miles from her house.',
  },
  {
    artist: 'angad-miglani', title: 'Walnut Ink Study', year: 2023,
    medium: 'Walnut ink on paper', materials: 'Walnut ink on found paper',
    w: 18, h: 14, price: 300, boldness: 3,
    styles: ['traditional'], colors: ['earth', 'neutral', 'monochrome'], moods: ['calm', 'cozy'],
    rooms: ['bedroom', 'office', 'hallway'],
    description: 'A branch study in home-made walnut ink, which starts warm brown and goes almost black where it pools.',
    note: 'I make the ink from the tree in my mother’s yard. It gets darker every year.',
  },
  {
    artist: 'angad-miglani', title: 'Quilt Logic', year: 2025,
    medium: 'Collage and ink on canvas', materials: 'Found paper, wheat paste, walnut ink, canvas',
    w: 44, h: 36, price: 1550, boldness: 6,
    styles: ['mixed-media', 'traditional'], colors: ['red', 'green', 'earth'], moods: ['cozy', 'inspiring'],
    rooms: ['living-room', 'dining-room'],
    description: 'A nine-block structure borrowed from quilting, built entirely from torn paper in oxide red and dusty green and drawn back into with ink.',
    note: 'The only formal training that mattered. She never called it composition.',
  },
  {
    artist: 'angad-miglani', title: 'Letters, Bought by the Pound', year: 2026,
    medium: 'Collage and ink on canvas', materials: 'Found correspondence, wheat paste, ink',
    w: 60, h: 42, price: 2800, boldness: 5,
    styles: ['mixed-media'], colors: ['earth', 'neutral', 'monochrome'], moods: ['sophisticated', 'cozy'],
    rooms: ['living-room', 'dining-room'],
    description: 'Five feet of layered correspondence — none of it legible, all of it real — pasted, sanded back, and unified under a wash of walnut ink.',
    note: 'I read every letter before I tore it. That felt like the minimum.',
  },
  {
    artist: 'angad-miglani', title: 'Branch, Walnut', year: 2024,
    medium: 'Walnut ink on paper', materials: 'Walnut ink on cotton rag',
    w: 20, h: 16, price: 520, boldness: 3,
    styles: ['traditional'], colors: ['green', 'earth', 'neutral'], moods: ['calm', 'cozy'],
    rooms: ['bedroom', 'hallway', 'office'],
    description: 'A single branch with seven leaves, drawn wet-into-wet so the ink pools at each junction. A green wash sits underneath.',
    note: 'Seven leaves because the eighth one made it a decoration.',
  },

  // -------------------------------------------------------------- Leo Zhang (6)
  {
    artist: 'leo-yang', title: 'One Pass', year: 2025,
    medium: 'Sumi ink on Xuan paper', materials: 'Hand-ground sumi ink on Xuan paper',
    w: 36, h: 48, price: 1400, boldness: 4, featured: true,
    styles: ['minimalist', 'abstract'], colors: ['monochrome', 'neutral', 'earth'], moods: ['calm', 'sophisticated'],
    rooms: ['living-room', 'office', 'bedroom'],
    mode: 6,
    description: 'One vertical stroke, four feet long, made standing, in a single unbroken movement. Where the brush ran dry, it was allowed to run dry.',
    note: 'If the stroke is wrong the sheet goes in the bin. This is the fourth sheet.',
  },
  {
    artist: 'leo-yang', title: 'Kept (No. 3 of 40)', year: 2025,
    medium: 'Sumi ink on Xuan paper', materials: 'Hand-ground sumi ink on Xuan paper',
    w: 14, h: 18, price: 430, boldness: 3,
    styles: ['minimalist'], colors: ['monochrome', 'neutral'], moods: ['calm', 'sophisticated'],
    rooms: ['office', 'bedroom', 'hallway'],
    mode: 6,
    description: 'Two short strokes crossing near the lower third, with a dry-brush tail on the second. Ink density shifts across the sheet where the paper drank unevenly.',
    note: 'I make about forty pieces a year and keep four. This was the third one I kept.',
  },
  {
    artist: 'leo-yang', title: 'Unlearning', year: 2024,
    medium: 'Sumi ink on Xuan paper', materials: 'Sumi ink on Xuan paper',
    w: 14, h: 18, price: 420, boldness: 3,
    styles: ['minimalist', 'abstract'], colors: ['neutral', 'monochrome', 'earth'], moods: ['calm'],
    rooms: ['bedroom', 'office', 'hallway'],
    mode: 6,
    description: 'A mark that was a character ten years ago and is now only a movement. Small, and deliberately unresolved.',
    note: 'A decade removing the meaning until the gesture was the only thing left.',
  },
  {
    artist: 'leo-yang', title: 'Loaded Brush', year: 2026,
    medium: 'Sumi ink and acrylic on canvas', materials: 'Sumi ink, acrylic, canvas',
    w: 48, h: 36, price: 2000, boldness: 6,
    styles: ['minimalist', 'abstract'], colors: ['monochrome', 'blue', 'neutral'], moods: ['sophisticated', 'dramatic'],
    rooms: ['living-room', 'office'],
    mode: 6,
    description: 'A fully loaded brush dragged once across four feet of canvas over a cold blue ground, spending its entire charge of ink in the first eighteen inches.',
    note: 'On canvas the ink behaves completely differently. It took two years to stop fighting that.',
  },
  {
    artist: 'leo-yang', title: 'Standing Work', year: 2026,
    medium: 'Sumi ink on Xuan paper', materials: 'Hand-ground sumi ink on Xuan paper',
    w: 70, h: 48, price: 4200, boldness: 5,
    styles: ['minimalist', 'abstract'], colors: ['neutral', 'monochrome'], moods: ['calm', 'sophisticated'],
    rooms: ['living-room'],
    mode: 6,
    description: 'Nearly six feet of paper with three marks on it, made in one pass over about eleven seconds. The largest sheet reachable across without stepping.',
    note: 'Eleven seconds. Two months of getting the paper flat enough to try.',
  },
  {
    artist: 'leo-yang', title: 'Hangzhou, Remembered', year: 2023,
    medium: 'Sumi ink on Xuan paper', materials: 'Sumi ink on Xuan paper',
    w: 16, h: 13, price: 330, boldness: 3,
    styles: ['minimalist'], colors: ['neutral', 'blue', 'monochrome'], moods: ['calm', 'cozy'],
    rooms: ['bedroom', 'hallway', 'dining-room'],
    mode: 6,
    description: 'A soft indigo wash under two ink marks, the only work in the practice that references a place directly.',
    note: 'The colour of the lake in the morning, as well as I can still recall it.',
  },
  // ---------------------------------------------------- Jake Janavicius (5)
  {
    artist: 'jake-janavicius', title: 'The Floor Meets Two Horizons', year: 2026,
    medium: 'Acrylic on panel', materials: 'Acrylic and gouache on birch panel',
    w: 40, h: 30, price: 1500, boldness: 7, mode: 1,
    styles: ['surreal', 'contemporary'], colors: ['purple', 'orange', 'neutral'],
    moods: ['dramatic', 'inspiring'], rooms: ['living-room', 'office'],
    description: 'A flat violet interior where the floor line resolves at two different heights depending which half you look at. Everything is painted clean and matte, because the disagreement only works if the surface stays calm.',
    note: 'Built the room in cardboard first and photographed it under a desk lamp. The mistake in the maquette became the painting.',
  },
  {
    artist: 'jake-janavicius', title: 'Chair, Waiting', year: 2025,
    medium: 'Gouache on paper', materials: 'Gouache on cotton rag',
    w: 18, h: 14, price: 380, boldness: 5,
    styles: ['surreal', 'minimalist'], colors: ['neutral', 'blue', 'monochrome'],
    moods: ['calm', 'dramatic'], rooms: ['bedroom', 'office', 'hallway'],
    description: 'One chair, one long shadow, and a wall that never quite arrives. Small, quiet, and slightly wrong in a way most people notice on the second look.',
    note: 'The shadow points at the light. Nobody has ever mentioned it unprompted.',
  },
  {
    artist: 'jake-janavicius', title: 'Second Staircase', year: 2026,
    medium: 'Acrylic on canvas', materials: 'Acrylic on cotton canvas',
    w: 48, h: 36, price: 1900, boldness: 8, mode: 1,
    styles: ['surreal', 'abstract'], colors: ['blue', 'purple', 'monochrome'],
    moods: ['dramatic', 'sophisticated'], rooms: ['living-room', 'dining-room'],
    description: 'Two flights of stairs sharing a landing they cannot both belong to, in cold blue and violet. The largest and most deliberately unresolved piece in the series.',
    note: 'I redrew the landing eleven times trying to make it work. Then I stopped trying.',
  },
  {
    artist: 'jake-janavicius', title: 'Doorway, No Wall', year: 2025,
    medium: 'Acrylic on panel', materials: 'Acrylic on birch panel',
    w: 24, h: 24, price: 720, boldness: 6, mode: 1,
    styles: ['surreal', 'contemporary'], colors: ['orange', 'neutral', 'red'],
    moods: ['playful', 'inspiring'], rooms: ['office', 'hallway', 'dining-room'],
    description: 'A freestanding door on an empty orange plain, casting a shadow four times its own length. Flat, bright, and completely straight-faced about it.',
    note: 'People keep asking what is behind it. That is the answer.',
  },
  {
    artist: 'jake-janavicius', title: 'Interior With Weather', year: 2026,
    medium: 'Acrylic on canvas', materials: 'Acrylic on canvas',
    w: 60, h: 44, price: 3900, boldness: 7, mode: 1,
    styles: ['surreal', 'contemporary'], colors: ['green', 'purple', 'neutral'],
    moods: ['dramatic', 'sophisticated'], rooms: ['living-room'],
    description: 'Five feet of sitting room with a horizon running through it and low cloud gathering near the ceiling. The furniture is rendered precisely, which is what makes the rest land.',
    note: 'A room I lived in for two years, painted from memory with the weather I remember rather than the weather there was.',
  },

  // ---------------------------------------------------------- Tinn Belly (5)
  {
    artist: 'tinn-belly', title: 'Two Passes, Misregistered', year: 2026,
    medium: 'Aerosol and stencil on panel', materials: 'Aerosol, hand-cut stencil, salvaged plywood',
    w: 36, h: 24, price: 1250, boldness: 9, mode: 1,
    styles: ['street', 'pop'], colors: ['red', 'vibrant', 'monochrome'],
    moods: ['energetic', 'playful'], rooms: ['living-room', 'office'],
    description: 'Two stencil passes in fluorescent red and black, deliberately out of register on a salvaged door panel. The grain shows through wherever the paint went thin.',
    note: 'Sanding the drips off would make it a poster. It is not a poster.',
  },
  {
    artist: 'tinn-belly', title: 'West Oakland, 4 AM', year: 2025,
    medium: 'Aerosol on canvas', materials: 'Aerosol and stencil on primed canvas',
    w: 30, h: 30, price: 840, boldness: 10, mode: 0,
    styles: ['street'], colors: ['orange', 'monochrome', 'yellow'],
    moods: ['energetic', 'dramatic'], rooms: ['office', 'living-room', 'dining-room'],
    description: 'A radial burst cut freehand and sprayed in three passes, with the overspray halo left exactly where it fell. Loud from across a room and louder up close.',
    note: 'Cut this one on a milk crate outside. The wobble in the rays is the crate.',
  },
  {
    artist: 'tinn-belly', title: 'Salvage No. 7', year: 2025,
    medium: 'Aerosol on found panel', materials: 'Aerosol, stencil, salvaged door panel',
    w: 16, h: 16, price: 320, boldness: 8, mode: 2,
    styles: ['street', 'mixed-media'], colors: ['green', 'monochrome', 'earth'],
    moods: ['energetic', 'cozy'], rooms: ['office', 'hallway', 'bedroom'],
    description: 'Concentric squares on a panel that was a cupboard door until 2024. The old hinge screw-holes are still in it and have not been filled.',
    note: 'Seventh panel off the same skip. The first six were worse.',
  },
  {
    artist: 'tinn-belly', title: 'Chevron Stack', year: 2026,
    medium: 'Aerosol and screenprint on panel', materials: 'Aerosol, screenprint, plywood',
    w: 44, h: 32, price: 1600, boldness: 9, mode: 3,
    styles: ['street', 'pop'], colors: ['blue', 'yellow', 'vibrant'],
    moods: ['energetic', 'playful'], rooms: ['living-room', 'office'],
    description: 'Three cut chevrons stacked in cobalt and lemon, the bottom one bleeding into the spray field behind it. Fast, flat, and unrepentant.',
    note: 'Took nine minutes. The stencil took two evenings.',
  },
  {
    artist: 'tinn-belly', title: 'Whole Wall', year: 2026,
    medium: 'Aerosol on canvas', materials: 'Aerosol, multi-layer stencil, canvas',
    w: 66, h: 44, price: 4200, boldness: 10, mode: 0,
    styles: ['street', 'pop'], colors: ['red', 'vibrant', 'orange'],
    moods: ['energetic', 'dramatic'], rooms: ['living-room'],
    description: 'Five and a half feet of layered stencil work, the largest piece made indoors rather than on a building. Six passes, four of them showing.',
    note: 'The only time I have worked this size with a roof over me. It felt like cheating.',
  },

  // ----------------------------------------------------- Julien Helleman (5)
  {
    artist: 'julien-helleman', title: 'Cutting, Third of May', year: 2026,
    medium: 'Sumi ink on handmade paper', materials: 'Hand-ground ink on handmade kozo paper',
    w: 20, h: 16, price: 540, boldness: 3,
    styles: ['traditional'], colors: ['green', 'earth', 'neutral'],
    moods: ['calm', 'cozy'], rooms: ['bedroom', 'office', 'hallway'],
    description: 'A single stem with eleven leaves, drawn wet-into-wet so the ink pools at every junction. Taken from the riverbank that morning and finished before it wilted.',
    note: 'Dated in the notebook, like all of them. I have never drawn the same specimen twice.',
  },
  {
    artist: 'julien-helleman', title: 'Riverbank, Low Water', year: 2025,
    medium: 'Ink and watercolour on paper', materials: 'Sumi ink and watercolour on cotton rag',
    w: 30, h: 22, price: 780, boldness: 4,
    styles: ['traditional', 'landscape'], colors: ['green', 'blue', 'earth'],
    moods: ['calm', 'inspiring'], rooms: ['living-room', 'bedroom', 'dining-room'],
    description: 'The Hudson in late August when the shallows go olive and the far bank flattens into a single wash. Ink first, colour after, nothing corrected.',
    note: 'Sat on a rock for two hours. The paper has a bit of the rock in it.',
  },
  {
    artist: 'julien-helleman', title: 'Seed Heads', year: 2025,
    medium: 'Sumi ink on paper', materials: 'Hand-ground ink on handmade paper',
    w: 14, h: 18, price: 300, boldness: 3,
    styles: ['traditional'], colors: ['earth', 'monochrome', 'neutral'],
    moods: ['calm', 'sophisticated'], rooms: ['bedroom', 'office', 'hallway'],
    description: 'Four dried seed heads at true size, each one a single loaded stroke and a handful of dry-brush marks. The palest work in the notebook.',
    note: 'Collected in November, drawn in November. They do not keep.',
  },
  {
    artist: 'julien-helleman', title: 'Two Ridges, Rain Coming', year: 2026,
    medium: 'Ink and watercolour on paper', materials: 'Sumi ink and watercolour on handmade paper',
    w: 44, h: 30, price: 1550, boldness: 5,
    styles: ['landscape', 'traditional'], colors: ['blue', 'neutral', 'green'],
    moods: ['calm', 'dramatic'], rooms: ['living-room', 'office'],
    description: 'Two ridgelines across the river with weather stacking behind the second one. The wash was laid in one pour and left to find its own edge.',
    note: 'It started raining about four minutes after this. That is the last mark.',
  },
  {
    artist: 'julien-helleman', title: 'The Whole Bank, September', year: 2026,
    medium: 'Ink and watercolour on paper', materials: 'Sumi ink and watercolour on handmade kozo',
    w: 56, h: 36, price: 2600, boldness: 5,
    styles: ['landscape', 'traditional'], colors: ['green', 'yellow', 'earth'],
    moods: ['calm', 'inspiring'], rooms: ['living-room', 'dining-room'],
    description: 'Nearly five feet of riverbank in early autumn, every plant drawn from a cutting taken the same week. The largest sheet the studio can hold flat.',
    note: 'Fourteen specimens, eleven days, one sheet. I did not let myself start over.',
  },

  // ------------------------------------------------------ Jack Kroothoep (5)
  {
    artist: 'jack-kroothoep', title: 'Two Hours, Marigny', year: 2026,
    medium: 'Oil on linen', materials: 'Oil on stretched linen',
    w: 30, h: 24, price: 900, boldness: 6,
    styles: ['portrait', 'impressionist'], colors: ['orange', 'earth', 'red'],
    moods: ['cozy', 'sophisticated'], rooms: ['living-room', 'hallway'],
    description: 'A neighbour painted from life in one sitting, in short broken strokes that only resolve when you step back. The north light in the room is doing most of the work.',
    note: 'They talked for the entire two hours and never once looked at the canvas.',
  },
  {
    artist: 'jack-kroothoep', title: 'Sitter, Half Turned', year: 2025,
    medium: 'Oil on panel', materials: 'Oil on gessoed panel',
    w: 18, h: 14, price: 400, boldness: 5,
    styles: ['portrait', 'impressionist'], colors: ['neutral', 'blue', 'earth'],
    moods: ['calm', 'sophisticated'], rooms: ['bedroom', 'office', 'hallway'],
    description: 'A small study made in forty minutes when the light started going. The face is barely there and the shoulder is the most finished part of it.',
    note: 'The ones I finish are usually worse than the ones the light finishes for me.',
  },
  {
    artist: 'jack-kroothoep', title: 'Bywater, Late Light', year: 2026,
    medium: 'Oil on linen', materials: 'Oil on linen',
    w: 40, h: 30, price: 1450, boldness: 7,
    styles: ['portrait', 'impressionist'], colors: ['orange', 'purple', 'red'],
    moods: ['dramatic', 'cozy'], rooms: ['living-room', 'dining-room'],
    description: 'A seated figure against a shotgun-house wall at the exact moment the light turns from gold to violet. The hottest palette in the series.',
    note: 'You get about eleven minutes of that light. This took three sittings to catch.',
  },
  {
    artist: 'jack-kroothoep', title: 'Anonymous, Green Room', year: 2025,
    medium: 'Oil on panel', materials: 'Oil on gessoed panel',
    w: 24, h: 20, price: 680, boldness: 5,
    styles: ['portrait', 'impressionist'], colors: ['green', 'neutral', 'earth'],
    moods: ['calm', 'cozy'], rooms: ['bedroom', 'dining-room'],
    description: 'A sitter almost absorbed into the sage wall behind them, painted with the same brush and mostly the same mixture.',
    note: 'They asked to be hard to recognise. Easiest brief I have ever had.',
  },
  {
    artist: 'jack-kroothoep', title: 'Everyone Who Sat In March', year: 2026,
    medium: 'Oil on linen', materials: 'Oil on stretched linen',
    w: 60, h: 42, price: 4500, boldness: 7,
    styles: ['portrait', 'impressionist'], colors: ['red', 'orange', 'neutral'],
    moods: ['inspiring', 'dramatic'], rooms: ['living-room'],
    description: 'Five feet of overlapping sitters from a single month, each painted in one session and then partly painted over by the next. The largest work in the practice.',
    note: 'Nine people. By the ninth I could not tell you whose mouth was whose.',
  },

  // ------------------------------------------------------ Parker Hayashi (5)
  {
    artist: 'parker-hayashi', title: 'Koreatown Signage No. 3', year: 2026,
    medium: 'Screenprint and vinyl on panel', materials: 'Screenprint, cut vinyl, found packaging',
    w: 30, h: 30, price: 880, boldness: 9, mode: 2,
    styles: ['pop', 'mixed-media'], colors: ['vibrant', 'yellow', 'red'],
    moods: ['playful', 'energetic'], rooms: ['living-room', 'office', 'dining-room'],
    description: 'A flat screenprinted ground layered with cut vinyl and packaging offcuts, in a palette lifted straight off a convenience-store awning on Western Avenue.',
    note: 'I photograph the signs, sample the colours, and then spend three weeks on something that took a sign painter an afternoon.',
  },
  {
    artist: 'parker-hayashi', title: 'Offcuts, Stacked', year: 2025,
    medium: 'Collage and screenprint on panel', materials: 'Found packaging, screenprint, panel',
    w: 18, h: 18, price: 400, boldness: 8, mode: 1,
    styles: ['pop', 'mixed-media'], colors: ['orange', 'blue', 'vibrant'],
    moods: ['playful', 'energetic'], rooms: ['office', 'hallway', 'dining-room'],
    description: 'Concentric rings printed over a bed of flattened packaging, so the corrugation reads through the ink in raking light.',
    note: 'Everything here was rubbish nine months ago. Some of it still smells faintly of detergent.',
  },
  {
    artist: 'parker-hayashi', title: 'Slow Work About Fast Things', year: 2026,
    medium: 'Screenprint and vinyl on canvas', materials: 'Screenprint, cut vinyl, primed canvas',
    w: 44, h: 34, price: 1700, boldness: 9, mode: 2,
    styles: ['pop', 'contemporary'], colors: ['red', 'yellow', 'vibrant'],
    moods: ['energetic', 'playful'], rooms: ['living-room', 'dining-room'],
    description: 'Six weeks of layering to make something that reads instantly. Flat colour, hard vinyl edges, and a surface with genuine depth if you stand close.',
    note: 'The title is what a friend said dismissively. I put it on the wall.',
  },
  {
    artist: 'parker-hayashi', title: 'Aisle Seven', year: 2025,
    medium: 'Screenprint on paper', materials: 'Four-colour screenprint on heavy stock',
    w: 24, h: 18, price: 620, boldness: 8, mode: 0,
    styles: ['pop'], colors: ['green', 'orange', 'vibrant'],
    moods: ['playful', 'energetic'], rooms: ['dining-room', 'office', 'hallway'],
    description: 'Four flat colours pulled in one edition, the palette taken from a shelf of instant noodles under fluorescent light.',
    note: 'The green is wrong on purpose. The real one was worse.',
  },
  {
    artist: 'parker-hayashi', title: 'Whole Front Window', year: 2026,
    medium: 'Screenprint and vinyl on canvas', materials: 'Screenprint, cut vinyl, canvas',
    w: 60, h: 40, price: 4000, boldness: 10, mode: 2,
    styles: ['pop', 'mixed-media'], colors: ['vibrant', 'red', 'yellow'],
    moods: ['energetic', 'playful'], rooms: ['living-room'],
    description: 'Five feet of layered signage colour, built to be legible from the far end of a room and rewarding from eighteen inches away.',
    note: 'Sixteen layers. I stopped counting the vinyl.',
  },

  // ------------------------------------------------------- Phillips Moore (5)
  {
    artist: 'phillips-moore', title: 'Eleven Miles, Dusk', year: 2026,
    medium: 'Platinum print', materials: 'Platinum-palladium print on cotton rag',
    w: 16, h: 12, price: 420, boldness: 2, mode: 1,
    styles: ['photography', 'minimalist'], colors: ['monochrome', 'neutral', 'blue'],
    moods: ['calm', 'sophisticated'], rooms: ['bedroom', 'office', 'hallway'],
    description: 'A four-minute exposure of the same stretch of highway shot since 2018, printed small so you have to walk up to it. The sky has gone completely smooth.',
    note: 'Small on purpose. If it were big you would look at it from the sofa and never go over.',
  },
  {
    artist: 'phillips-moore', title: 'Water Tank, No Wind', year: 2025,
    medium: 'Platinum print', materials: 'Platinum-palladium print on cotton rag',
    w: 20, h: 16, price: 560, boldness: 2, mode: 1,
    styles: ['photography', 'minimalist'], colors: ['neutral', 'monochrome', 'earth'],
    moods: ['calm'], rooms: ['bedroom', 'hallway', 'office'],
    description: 'One tank, one horizon, and nothing else in the frame that survived four minutes of exposure.',
    note: 'There were three cows. Four minutes took care of them.',
  },
  {
    artist: 'phillips-moore', title: 'Fence Line', year: 2026,
    medium: 'Archival pigment print', materials: 'Archival pigment on matte cotton',
    w: 36, h: 24, price: 1150, boldness: 3, mode: 1,
    styles: ['photography', 'minimalist'], colors: ['neutral', 'earth', 'monochrome'],
    moods: ['calm', 'sophisticated'], rooms: ['living-room', 'bedroom', 'office'],
    description: 'Wire and posts running dead flat to the edge of the frame, with the plains going pale behind them. The only work here printed large.',
    note: 'I broke my own rule for this one. It needed the room.',
  },
  {
    artist: 'phillips-moore', title: 'Road, Held', year: 2025,
    medium: 'Platinum print', materials: 'Platinum-palladium print on cotton rag',
    w: 14, h: 18, price: 380, boldness: 2, mode: 1,
    styles: ['photography', 'minimalist'], colors: ['monochrome', 'neutral'],
    moods: ['calm', 'dramatic'], rooms: ['bedroom', 'office', 'hallway'],
    description: 'The highway seen end-on at last light, reduced by the exposure to two tones and a seam.',
    note: 'Same mile marker as always. Different four minutes.',
  },
  {
    artist: 'phillips-moore', title: 'Marfa, The Long Version', year: 2026,
    medium: 'Archival pigment print', materials: 'Archival pigment on matte cotton rag',
    w: 60, h: 36, price: 2900, boldness: 4, mode: 1,
    styles: ['photography', 'landscape'], colors: ['neutral', 'orange', 'monochrome'],
    moods: ['calm', 'inspiring'], rooms: ['living-room', 'dining-room'],
    description: 'Five feet of high plains at the moment the sky stops being blue and has not yet decided what else to be. Eight years of the same view, printed once at size.',
    note: 'The only frame from the whole project I have ever printed above twenty inches.',
  },

  // ------------------------------------------------------ Parker Wilding (5)
  {
    artist: 'parker-wilding', title: 'Bridger, Four Bands', year: 2026,
    medium: 'Oil and cold wax on canvas', materials: 'Oil, cold wax, stretched canvas',
    w: 40, h: 30, price: 1400, boldness: 5, mode: 0,
    styles: ['landscape', 'abstract'], colors: ['blue', 'neutral', 'purple'],
    moods: ['calm', 'sophisticated'], rooms: ['living-room', 'bedroom', 'office'],
    description: 'The Bridger range reduced to four bands of colour and the intervals between them. Cold wax gives the whole surface a matte, plastered quality.',
    note: 'A specific morning in March. The title is the only place that information survives.',
  },
  {
    artist: 'parker-wilding', title: 'Gallatin, Snow Line', year: 2025,
    medium: 'Oil on panel', materials: 'Oil and cold wax on birch panel',
    w: 24, h: 18, price: 640, boldness: 4, mode: 0,
    styles: ['landscape', 'abstract'], colors: ['neutral', 'blue', 'monochrome'],
    moods: ['calm'], rooms: ['bedroom', 'office', 'hallway'],
    description: 'Three bands, one of them almost white, at the height where the snow stopped that week. Quiet enough to live with in a small room.',
    note: 'The snow line moves about forty feet a day in April. This is one day of it.',
  },
  {
    artist: 'parker-wilding', title: 'Paradise Valley, Late', year: 2026,
    medium: 'Oil and cold wax on canvas', materials: 'Oil, cold wax, canvas',
    w: 48, h: 34, price: 1800, boldness: 6, mode: 0,
    styles: ['landscape', 'abstract'], colors: ['orange', 'earth', 'purple'],
    moods: ['inspiring', 'sophisticated'], rooms: ['living-room', 'dining-room'],
    description: 'Five bands running warm to cool across four feet, taken from the valley an hour before the light goes. The weight of each interval is the whole subject.',
    note: 'Painted with the barn doors open, which is the only way I can judge the top band.',
  },
  {
    artist: 'parker-wilding', title: 'Ridge, Reduced', year: 2025,
    medium: 'Oil on panel', materials: 'Oil and cold wax on panel',
    w: 16, h: 12, price: 340, boldness: 3, mode: 0,
    styles: ['abstract', 'landscape'], colors: ['green', 'neutral', 'earth'],
    moods: ['calm', 'cozy'], rooms: ['bedroom', 'hallway', 'office'],
    description: 'A study: two greens, one grey, and the exact height at which one becomes the other.',
    note: 'Forty of these a year. This is the size where I decide whether an interval works.',
  },
  {
    artist: 'parker-wilding', title: 'The Whole Range, One Morning', year: 2026,
    medium: 'Oil and cold wax on canvas', materials: 'Oil, cold wax, stretched canvas',
    w: 72, h: 42, price: 4800, boldness: 6, mode: 0,
    styles: ['landscape', 'abstract'], colors: ['blue', 'purple', 'neutral'],
    moods: ['calm', 'inspiring'], rooms: ['living-room'],
    description: 'Six feet of ridgeline compressed into six bands, from a single morning in October when the whole range was visible at once. The largest work in the practice.',
    note: 'That happens maybe five times a year. I had the canvas ready for two of them.',
  },
]
